#!/bin/sh
set -e

BIN_DIR="/opt/sparkd/bin"
LINK_DIR="/usr/local/bin"

mkdir -p "$LINK_DIR"
for bin in "$BIN_DIR/"*; do
    name="$(basename "$bin")"
    ln -sf "$bin" "$LINK_DIR/$name"
done

echo ""
echo "  sparkd installed. Run: sparkctl --help"
echo ""
