#ifndef SPARK_CONSTS_H
#define SPARK_CONSTS_H

#define SPARK_SERIAL_PORT_STRLEN 256

#define SPARK_MIDI_PORT_STRLEN 256
#define SPARK_MIDI_MAX_DEVICES 32

#define SPARK_DMX_UNIVERSE_SIZE 512

#define SPARK_SCENES_MAX_COUNT 2048 /* 16*128 */
#define SPARK_ACTIVE_SCENES_MAX 32

#endif